apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: samchan930423/reactdocker:latest
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  type: NodePort
  ports:
    - name: http  # Name for port 80
      port: 80
      targetPort: 80
      nodePort: 30001  # Expose on this port
    - name: https  # Name for port 443
      port: 443
      targetPort: 443
      nodePort: 30443  # Expose on this port
  selector:
    app: react-frontend
